username: admin
password: infoblox
auth_server: 10.197.38.101
rad1_ip: 10.197.38.101
rad2_ip: 10.36.201.7
auth_server_fqdn: authserver.inblr.infoblox.com
radius_username: user1_radius
radius_password: infoblox
tacacs_username: user1_tacacs
tacacs_password: infoblox
ad_username: manojrg
ad_password: Infoblox@123
ldap_username: user1_ldap
ldap_password: infoblox
ad_domain: ad19187.com
ad_ip: 10.34.98.56
resolver: 10.195.3.10
resolver_ad: 10.34.98.50
ad_domain_ssl: ad19181.com
ad_fqdn: win-5dcblgu6lih.ad19181.com
ad_ip_ssl: 10.34.98.50
ad_username_ssl: Administrator
ad_pass_ssl: Infoblox123
ad_nested_user1: user1_test
ad_nested_user2: user2_test
additional_search_path: ou=test2,ou=test1,DC=19181,DC=com
